### ISSUE TITLE
QoL improvements

### ISSUE THREAD

**Issue by Chris-Is-Awesome** [Extra-2-Dew/ArchipelagoRandomizer#20]
Various quality of life improvements:

- [x] Reduce wait for Maze of Steel cow UFO
- [x] Speed up sweaty pathing enemies
- [x] Make Frozen Court spirits more convenient
  - [x] Have them both active at all times, regardless of time of day
  - [x] They don't disappear while offscreen, but only open the cave when onscreen

**Comment by GameWyrm** [comment]
For FC spirits, it was decided to not speed them up, but to have them available at any time of day. They don't disappear while off-screen, but they don't open their cave until on-screen again.

**Comment by Chris-Is-Awesome** [comment]
Done in #39
