### ISSUE TITLE
Open Dreamworld opens Quietus

### ISSUE THREAD

**Issue by GameWyrm** [Extra-2-Dew/ArchipelagoRandomizer#27]
Open Dreamworld setting should not have Quietus start open, as decided by the randomizer community.

**Comment by Chris-Is-Awesome** [comment]
Fixed in [aef297c](https://github.com/Extra-2-Dew/ArchipelagoRandomizer/commit/aef297ca51c0a07daacb1ebf1c5bbbd6e2aad797)
