### ISSUE TITLE
Respawns revert item overrides

### ISSUE THREAD

**Issue by GameWyrm** [Extra-2-Dew/ArchipelagoRandomizer#28]
It appears that certain types of respawns can cause item restrictions to be changed, such as ignoring Dreamworld Dungeons Do Not Change Items setting in Dreamworld dungeons, or removing EFCS after dying in The Promised Remedy.

**Comment by Chris-Is-Awesome** [comment]
Fixed in [7f5ada7](https://github.com/Extra-2-Dew/ArchipelagoRandomizer/commit/7f5ada7d4c09f197b7025c9838a3040c5c1b5f39)
