### ISSUE TITLE
Scouting Data is maintained between files

### ISSUE THREAD

**Issue by GameWyrm** [Extra-2-Dew/ArchipelagoRandomizer#30]
If you load a second Archipelago randomized save file in a single session, all the item info used for Chests Match Contents and item message boxes use the data from the first file.

**Comment by Chris-Is-Awesome** [comment]
Fixed with commit [e58b648](https://github.com/Extra-2-Dew/ArchipelagoRandomizer/commit/e58b648c87e5d44e6b873c69e5aec2cbde530ffc)
